### ISSUE TITLE
Python 3 update : Tkinter renamed to tkinter 

### ISSUE THREAD

**Issue by mskb01** [HIPS/pgmult#12]
Hi, the Python 3 update of pgmult is causing the 'Import Error: no module named Tkinter'. Turns out it has been renamed to tkinter?

**Comment by slinderman** [comment]
I don't see any usages of `TKinter` in the repository. Can you send a stack trace of where it is being imported?

**Comment by mskb01** [comment]
Oh sorry, I thought I pasted the stacktrace. It seems to arise from six.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmult/lda.py", line 17, in <module>
    from pybasicbayes.distributions import Gaussian
  File "pybasicbayes-0.2.1-py2.7-linux-x86_64.egg/pybasicbayes/**init**.py", line 2, in <module>
    from . import abstractions, distributions, models, util
  File "pybasicbayes-0.2.1-py2.7-linux-x86_64.egg/pybasicbayes/abstractions.py", line 9, in <module>
    from pybasicbayes.util.stats import combinedata
  File "pybasicbayes-0.2.1-py2.7-linux-x86_64.egg/pybasicbayes/util/**init**.py", line 3, in <module>
    from . import general, plot, stats, text
  File "pybasicbayes-0.2.1-py2.7-linux-x86_64.egg/pybasicbayes/util/plot.py", line 4, in <module>
    from matplotlib import pyplot as plt
  File "matplotlib-2.0.0b4-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "matplotlib-2.0.0b4-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "matplotlib-2.0.0b4-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "six-1.10.0-py2.7.egg/six.py", line 203, in load_module
    mod = mod._resolve()
  File "six-1.10.0-py2.7.egg/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "six-1.10.0-py2.7.egg/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named Tkinter
